// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seyhioicqhggodnmrnsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNleWhpb2ljcWhnZ29kbm1ybnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTgyMjcsImV4cCI6MjA2MzY3NDIyN30.6A35KAOL2uHxM7SoSH6K69TCnW3KlQOtKwCq8Nuuyh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);